language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
matrix:
  allow_failures:
    - python: "2.7"
    - python: "3.4"
  fast_finish: true

# Route build to container-based infrastructu
sudo: required
# Cache the dependencies installed by pip
cache: pip

# Install defaults to "pip install -r requirements.txt"

# Commands that prepare things for the test
# install apel using experimental setup up script
before_script:
  - wget https://github.com/gregcorbett/apel/archive/apel-setup-script.zip
  - unzip apel-setup-script.zip
  - cd apel-apel-setup-script
  - sudo python setup.py install
  - cp /usr/local/lib/python2.7/dist-packages/apel-1.5.1-py2.7.egg /home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/apel-1.5.1-py2.6.egg
  - export PYTHONPATH=$PYTHONPATH:`pwd -P`:/home/travis/virtualenv/python2.6.9/lib/python2.6:/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages

# Command to run tests
script: coverage run --source='.' manage.py test

after_success: coveralls
